### ISSUE TITLE
cannot import name 'Session' from 'tensorflow'

### ISSUE THREAD

**Issue by bohniti** [gaborvecsei/Swiss-Army-Tensorboard#1]
Dear Developer,

First of all, I low swiss-army-tensorboard. Great work!
Unfortunately, the code is no longer working with TF 2.0 because the tf session is no longer available on this version. 
Or more precisely its location in the API has changed such it is no longer stand-alone. 
I will try to fix it by myself and will send you a pull request as soon as I had fixed it.

**Comment by gaborvecsei** [comment]
Dear @bohniti,

Thank you! Unfortunately this code works only with Tensorflow 1.X. In the future it will be updated to TF 2, but I don't have time for that right now, so a PR would be appreciated 👍

**Comment by bohniti** [comment]
Okay, thanks for letting me know. I have changed a few things already, but I stuck on a problem with the sessions.
The next four weeks I am swamped because of the university. Afterwards, I will fix this. Stay tuned  👯
